from __future__ import annotations

from app.schemas.source_catalog import (
    SourceCatalogCategory,
    SourceCatalogEntry,
    SourceCatalogResponse,
)


def get_source_catalog() -> SourceCatalogResponse:
    categories = _build_categories()
    total_sources = sum(len(category.sources) for category in categories)
    return SourceCatalogResponse(
        categories=categories,
        total_categories=len(categories),
        total_sources=total_sources,
    )


def _entry(
    source_id: str,
    display_name: str,
    category: str,
    feasibility_status: str,
    acquisition_modes: list[str],
    allowed_data_types: list[str],
    forbidden_data_types: list[str],
    current_status: str,
    compliance_notes: str,
    next_action: str,
    priority: str,
) -> SourceCatalogEntry:
    return SourceCatalogEntry(
        source_id=source_id,
        display_name=display_name,
        category=category,
        feasibility_status=feasibility_status,
        acquisition_modes=acquisition_modes,  # type: ignore[arg-type]
        allowed_data_types=allowed_data_types,  # type: ignore[arg-type]
        forbidden_data_types=forbidden_data_types,
        current_status=current_status,
        compliance_notes=compliance_notes,
        next_action=next_action,
        priority=priority,
    )


def _build_categories() -> list[SourceCatalogCategory]:
    return [
        SourceCatalogCategory(
            category_id="video_platforms",
            display_name="Video Platforms",
            description="Public video/post metadata and comments through official APIs, OAuth, user upload, or mock fixtures.",
            sources=[
                _entry(
                    "youtube",
                    "YouTube",
                    "video_platforms",
                    "green",
                    ["official_api_public", "user_upload", "mock_fixture"],
                    ["video", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["private_messages", "oauth_private_data", "cookie_session_data"],
                    "real_capable_when_configured",
                    "Official YouTube Data API v3 only; default mock mode; cache and tiny-limit guardrails.",
                    "Keep local key in ignored environment files and use cached tiny demos.",
                    "high",
                ),
                _entry(
                    "douyin",
                    "Douyin",
                    "video_platforms",
                    "yellow",
                    ["official_api_oauth", "user_upload", "mock_fixture"],
                    ["video", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["cookie_session_data", "captcha_bypass_data", "unauthorized_item_comments"],
                    "web_app_oauth_and_item_comment_pending",
                    "Developer access recorded, but OAuth, redirect URI, whitelist, token flow, item.comment, and item_id source remain unverified.",
                    "Verify Douyin console gates before any real call.",
                    "high",
                ),
                _entry(
                    "bilibili",
                    "Bilibili",
                    "video_platforms",
                    "yellow",
                    ["official_api_oauth", "user_upload", "mock_fixture"],
                    ["video", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["scraped_dynamic_comments", "cookie_session_data", "private_data"],
                    "official_permission_pending",
                    "Use official permission or user-provided lawful exports only.",
                    "Verify official API approval and capture sanitized fixtures.",
                    "high",
                ),
                _entry(
                    "kuaishou",
                    "Kuaishou",
                    "video_platforms",
                    "red",
                    ["official_api_oauth", "user_upload", "mock_fixture"],
                    ["video", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["direct_crawl", "cookie_session_data", "livestream_private_data"],
                    "official_permission_required",
                    "No direct crawling; official API permission is required before real use.",
                    "Confirm official data scope before implementation.",
                    "medium",
                ),
                _entry(
                    "tiktok",
                    "TikTok",
                    "video_platforms",
                    "yellow",
                    ["official_api_oauth", "user_upload", "data_vendor", "mock_fixture"],
                    ["video", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["scraping", "cookie_session_data", "private_data"],
                    "future_official_or_vendor_source",
                    "Treat as future official API/vendor/user-upload source; no current adapter.",
                    "Research official API/vendor options later.",
                    "low",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="news_media_sites",
            display_name="News / Media Sites",
            description="Public articles and visible public metadata from media sites, RSS, approved APIs, or fixture-reviewed public parsers.",
            sources=[
                _entry(
                    "the_paper",
                    "The Paper / Pengpai",
                    "news_media_sites",
                    "green",
                    ["public_parser", "manual_url", "user_upload", "mock_fixture"],
                    ["article", "title", "body_text", "interaction_metric"],
                    ["login_required_comments", "dynamic_private_data"],
                    "fixture_parser_available",
                    "Fixture-first parser exists; live public fetch remains separately guarded.",
                    "Keep fixture-first and review any live pilot before use.",
                    "high",
                ),
                _entry(
                    "jiemian",
                    "Jiemian",
                    "news_media_sites",
                    "green",
                    ["public_parser", "manual_url", "user_upload", "mock_fixture"],
                    ["article", "title", "body_text"],
                    ["login_required_comments", "dynamic_private_data"],
                    "fixture_parser_available",
                    "Fixture parser covers article text; comments are not collected without compliant public access.",
                    "Keep fixture-first.",
                    "medium",
                ),
                _entry(
                    "media_news_general",
                    "36Kr / Huxiu / Sina / NetEase / Tencent News / Xinhua / People / Reuters / BBC / The Guardian",
                    "news_media_sites",
                    "yellow",
                    ["public_parser", "manual_url", "search_discovery", "user_upload", "data_vendor"],
                    ["article", "title", "body_text", "search_result"],
                    ["paywalled_content", "login_required_comments", "copyright_bulk_copying"],
                    "planned_source_family",
                    "Prefer RSS, official feeds, user-provided URLs, or reviewed public parsers with small limits.",
                    "Add source-specific parser/feeds only after compliance review.",
                    "medium",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="forums_communities",
            display_name="Forums / Communities",
            description="Public thread/post/comment evidence from fixture-reviewed public parsers, official APIs, or user-provided exports.",
            sources=[
                _entry(
                    "hupu_tieba_nga_maimai",
                    "Hupu / Tieba / NGA / Maimai",
                    "forums_communities",
                    "green",
                    ["public_parser", "user_upload", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["login_required_content", "cookie_session_data", "anti_bot_bypass_data"],
                    "fixture_parser_available",
                    "Fixture-first parsers exist for public thread-style examples; no broad live crawling.",
                    "Keep fixture regression coverage and manual evidence path.",
                    "high",
                ),
                _entry(
                    "v2ex",
                    "V2EX",
                    "forums_communities",
                    "yellow",
                    ["public_parser", "manual_url", "user_upload", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text"],
                    ["login_required_content", "cookie_session_data"],
                    "planned_public_parser_candidate",
                    "Requires parser review and public-page compliance checks before live use.",
                    "Consider fixture-only profile first.",
                    "low",
                ),
                _entry(
                    "reddit",
                    "Reddit",
                    "forums_communities",
                    "yellow",
                    ["official_api_public", "user_upload", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["public_page_scraping_as_bypass", "cookie_session_data"],
                    "api_approval_pending",
                    "Real API mode remains disabled until official approval.",
                    "Wait for approval; do not scrape as a bypass.",
                    "medium",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="qa_sites",
            display_name="Q&A Sites",
            description="Question, answer, and comment evidence through official APIs, public-parser review, or user-provided exports.",
            sources=[
                _entry(
                    "zhihu",
                    "Zhihu",
                    "qa_sites",
                    "red",
                    ["official_api_oauth", "user_upload", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text"],
                    ["scraping", "cookie_session_data", "private_account_data"],
                    "official_permission_required",
                    "Current adapter is mock-only; no real Zhihu collection.",
                    "Verify official API access before real implementation.",
                    "medium",
                ),
                _entry(
                    "stack_exchange_quora",
                    "Stack Exchange / Quora",
                    "qa_sites",
                    "yellow",
                    ["official_api_public", "public_parser", "manual_url", "user_upload", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text"],
                    ["login_required_content", "private_data"],
                    "future_source_family",
                    "Stack Exchange has official API options; Quora requires careful permission review.",
                    "Research source-specific rules before implementation.",
                    "low",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="complaint_review_sites",
            display_name="Complaint / Review Sites",
            description="User review and complaint records from official APIs, public feeds, user upload, or vendor data.",
            sources=[
                _entry(
                    "reviews_complaints",
                    "Black Cat Complaint / App Store Reviews / Google Play Reviews / Steam Reviews / Trustpilot",
                    "complaint_review_sites",
                    "yellow",
                    ["official_api_public", "public_parser", "manual_url", "user_upload", "data_vendor", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["private_order_data", "login_required_personal_data", "scraping_bypass_data"],
                    "planned_source_family",
                    "Use official APIs/feeds where available, or user-provided exports with lawful-source attestation.",
                    "Design source-specific import and redaction checks later.",
                    "medium",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="finance_investor_forums",
            display_name="Finance / Investor Forums",
            description="Public investor discussion evidence with additional caution around financial interpretation and data licensing.",
            sources=[
                _entry(
                    "finance_forums",
                    "Xueqiu / Eastmoney Guba / StockTwits",
                    "finance_investor_forums",
                    "yellow",
                    ["official_api_public", "public_parser", "manual_url", "user_upload", "data_vendor", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["trading_advice_profiles", "private_account_data", "scraping_bypass_data"],
                    "planned_source_family",
                    "Use only public/forum evidence and avoid financial advice or account-level scoring.",
                    "Review licensing and official API/data vendor paths.",
                    "low",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="social_platforms",
            display_name="Social Platforms",
            description="Public social posts/comments only through official API/OAuth, user upload, or vendor integration.",
            sources=[
                _entry(
                    "weibo",
                    "Weibo",
                    "social_platforms",
                    "yellow",
                    ["official_api_oauth", "user_upload", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["cookie_session_data", "private_messages", "scraping_bypass_data"],
                    "company_age_requirement_pending",
                    "Official API access is blocked by current eligibility requirements.",
                    "Revisit after eligibility changes or approved vendor/user export path.",
                    "medium",
                ),
                _entry(
                    "x_twitter_bluesky_mastodon",
                    "X/Twitter / Bluesky / Mastodon",
                    "social_platforms",
                    "yellow",
                    ["official_api_public", "official_api_oauth", "manual_url", "user_upload", "data_vendor", "mock_fixture"],
                    ["post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["scraping_bypass_data", "private_messages", "cookie_session_data"],
                    "future_source_family",
                    "Use official APIs or user-provided datasets; do not scrape behind login or rate limits.",
                    "Research API terms and public-data limits source by source.",
                    "low",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="search_discovery",
            display_name="Search Discovery",
            description="Approved search/discovery metadata sources that find candidate public evidence without scraping search result pages.",
            sources=[
                _entry(
                    "search_discovery",
                    "GDELT / Google Programmable Search / Search Discovery",
                    "search_discovery",
                    "yellow",
                    ["search_discovery", "data_vendor", "manual_url", "mock_fixture"],
                    ["search_result", "title", "body_text"],
                    ["serp_scraping", "captcha_bypass_data", "proxy_evasion_data"],
                    "schema_ready_no_connector",
                    "Discovery mode should use approved APIs/vendors or manual review, not scraping.",
                    "Design provider-specific connector only after terms review.",
                    "medium",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="rss",
            display_name="RSS",
            description="Public RSS/Atom feed metadata and article links from sources whose terms allow feed consumption.",
            sources=[
                _entry(
                    "rss",
                    "RSS",
                    "rss",
                    "green",
                    ["public_parser", "manual_url", "user_upload", "mock_fixture"],
                    ["search_result", "article", "title", "body_text"],
                    ["private_feeds", "paywalled_content"],
                    "planned_low_risk_source",
                    "RSS is suitable for public feed metadata when feed terms allow it.",
                    "Add RSS fixture/import pilot when needed.",
                    "medium",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="user_uploaded_datasets",
            display_name="User-Uploaded Datasets",
            description="CSV, Excel, or JSON records supplied by the user with lawful-source attestation and secret screening.",
            sources=[
                _entry(
                    "uploaded_datasets",
                    "CSV / Excel / JSON Upload",
                    "user_uploaded_datasets",
                    "green",
                    ["user_upload", "mock_fixture"],
                    ["uploaded_record", "article", "post", "comment", "reply", "title", "body_text", "interaction_metric"],
                    ["credential_values", "private_data_without_permission"],
                    "manual_evidence_shape_ready",
                    "Allowed only when user attests lawful source and secrets/private data are excluded.",
                    "Add CSV/Excel UI import after manual evidence attach QA.",
                    "high",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="manual_url_evidence",
            display_name="Manual URL Evidence",
            description="User-entered public URL, title/body, video description, and comment snippets without automatic page fetching.",
            sources=[
                _entry(
                    "manual_url",
                    "Manual URL Evidence",
                    "manual_url_evidence",
                    "green",
                    ["manual_url", "user_upload", "mock_fixture"],
                    ["article", "video", "post", "comment", "title", "body_text"],
                    ["automatic_fetch_without_review", "private_or_login_required_content"],
                    "manual_attach_supported",
                    "Manual URL evidence stores user-provided metadata; it does not fetch the URL by itself.",
                    "Add a UI form only if demos need it.",
                    "high",
                ),
            ],
        ),
        SourceCatalogCategory(
            category_id="data_vendor_future_integration",
            display_name="Data Vendor Future Integration",
            description="Licensed vendor feeds that may provide public-opinion evidence after contract, retention, and redaction review.",
            sources=[
                _entry(
                    "data_vendor",
                    "Data Vendor Future Integration",
                    "data_vendor_future_integration",
                    "yellow",
                    ["data_vendor", "user_upload", "mock_fixture"],
                    ["uploaded_record", "article", "post", "comment", "reply", "search_result", "interaction_metric"],
                    ["unlicensed_payloads", "credential_values", "private_data_without_contract"],
                    "future_contractual_source",
                    "Vendor integration requires contract, data dictionary, retention rules, and redaction checks.",
                    "Keep as future adapter behind mocked fixtures.",
                    "low",
                ),
            ],
        ),
    ]
